name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PyTest
        run: |
          python -m pytest -v tests/

      - name: Run ML Pipeline Update
        run: |
          python run.py -mode update

      - name: Upload Logs Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-logs
          path: pipeline.log
          retention-days: 5

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-model
          path: models/best_model.pkl
          retention-days: 5
